version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dynastic
    ports:
      - 1000:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
